version: '3.8'

services:
  # PostgreSQL - Data Warehouse
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    environment:
      # Credentials for database access
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: datawarehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./warehouse/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - ecommerce-network

  # Zookeeper - Required by Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ecommerce-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"
    networks:
      - ecommerce-network

  # Kafka - Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ecommerce-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_MESSAGE_FORMAT_VERSION: "3.0"
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: "CreateTime"
    ports:
      - "9093:9092"
    networks:
      - ecommerce-network
  
  # kafka-init:
  #   image: confluentinc/cp-kafka:7.4.0
  #   depends_on:
  #     - kafka
  #   command: >
  #     bash -c "
  #     echo 'In attesa che Kafka sia pronto...' &&
  #     cub kafka-ready -b kafka:9092 1 30 &&
  #     echo 'Creazione topic...' &&
  #     kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic order-created --partitions 3 --replication-factor 1 &&
  #     echo 'Topic creato con successo!'"
  #     "

  # Kafka UI - Optional monitoring interface
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ecommerce-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - ecommerce-network


volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge
